# Generated by Django 5.0.2 on 2025-03-18 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tổng tiền')),
                ('insurance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Số tiền bảo hiểm chi trả')),
                ('patient_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Số tiền bệnh nhân phải trả')),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('cancelled', 'Đã hủy'), ('refunded', 'Đã hoàn tiền')], default='pending', max_length=10, verbose_name='Trạng thái')),
                ('payment_method', models.CharField(choices=[('cash', 'Tiền mặt'), ('card', 'Thẻ'), ('transfer', 'Chuyển khoản'), ('insurance', 'Bảo hiểm')], default='cash', max_length=10, verbose_name='Phương thức thanh toán')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày thanh toán')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL, verbose_name='Bệnh nhân')),
                ('prescription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='pharmacy.prescription', verbose_name='Đơn thuốc')),
            ],
            options={
                'verbose_name': 'Hóa đơn',
                'verbose_name_plural': 'Hóa đơn',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Thu'), ('expense', 'Chi')], max_length=10, verbose_name='Loại giao dịch')),
                ('category', models.CharField(choices=[('medicine', 'Thuốc'), ('service', 'Dịch vụ'), ('salary', 'Lương'), ('utility', 'Tiện ích'), ('other', 'Khác')], max_length=10, verbose_name='Danh mục')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Số tiền')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('transaction_date', models.DateTimeField(verbose_name='Ngày giao dịch')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.bill', verbose_name='Hóa đơn')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Giao dịch',
                'verbose_name_plural': 'Giao dịch',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
