# Generated by Django 5.0.2 on 2025-03-21 11:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('pos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Số tiền')),
                ('expense_type', models.CharField(choices=[('inventory', 'Nhập hàng'), ('salary', 'Lương nhân viên'), ('rent', 'Tiền thuê'), ('utility', 'Tiện ích'), ('equipment', 'Thiết bị'), ('marketing', 'Marketing'), ('other', 'Khác')], default='other', max_length=20, verbose_name='Loại chi phí')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày ghi nhận')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='Người ghi nhận')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.transaction', verbose_name='Giao dịch')),
            ],
            options={
                'verbose_name': 'Chi phí',
                'verbose_name_plural': 'Chi phí',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Hàng ngày'), ('weekly', 'Hàng tuần'), ('monthly', 'Hàng tháng'), ('quarterly', 'Hàng quý'), ('yearly', 'Hàng năm'), ('custom', 'Tùy chỉnh')], default='monthly', max_length=20, verbose_name='Loại báo cáo')),
                ('start_date', models.DateTimeField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateTimeField(verbose_name='Ngày kết thúc')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tổng doanh thu')),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tổng chi phí')),
                ('net_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Thu nhập ròng')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo báo cáo')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo báo cáo')),
            ],
            options={
                'verbose_name': 'Báo cáo tài chính',
                'verbose_name_plural': 'Báo cáo tài chính',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Số tiền')),
                ('revenue_type', models.CharField(choices=[('sale', 'Bán hàng'), ('service', 'Dịch vụ'), ('other', 'Khác')], default='sale', max_length=20, verbose_name='Loại doanh thu')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày ghi nhận')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to=settings.AUTH_USER_MODEL, verbose_name='Người ghi nhận')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenues', to='pos.sale', verbose_name='Hóa đơn bán hàng')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenues', to='finance.transaction', verbose_name='Giao dịch')),
            ],
            options={
                'verbose_name': 'Doanh thu',
                'verbose_name_plural': 'Doanh thu',
                'ordering': ['-date'],
            },
        ),
    ]
