# Generated by Django 5.0.2 on 2025-05-11 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('user', 'Người dùng'), ('bot', 'Chatbot')], max_length=4, verbose_name='Loại tin nhắn')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian gửi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_messages', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Tin nhắn Bot',
                'verbose_name_plural': 'Tin nhắn Bot',
                'ordering': ['sent_at'],
            },
        ),
    ]
