# Generated by Django 5.0.2 on 2025-05-19 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_botmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_context', models.JSONField(default=dict, help_text='Lưu trữ ngữ cảnh cuộc trò chuyện dưới dạng JSON', verbose_name='Ngữ cảnh cuộc trò chuyện')),
                ('max_context_length', models.IntegerField(default=10, help_text='Số lượng tin nhắn tối đa được lưu trong ngữ cảnh', verbose_name='Độ dài tối đa của ngữ cảnh')),
                ('last_interaction', models.DateTimeField(auto_now=True, verbose_name='Thời gian tương tác cuối cùng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_memories', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Bộ nhớ Chat',
                'verbose_name_plural': 'Bộ nhớ Chat',
                'ordering': ['-last_interaction'],
            },
        ),
    ]
