# Generated by Django 5.0.2 on 2025-03-18 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnosis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Danh mục thuốc',
                'verbose_name_plural': 'Danh mục thuốc',
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên thuốc')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('composition', models.TextField(verbose_name='Thành phần')),
                ('usage', models.TextField(verbose_name='Cách dùng')),
                ('dosage', models.TextField(verbose_name='Liều lượng')),
                ('side_effects', models.TextField(blank=True, verbose_name='Tác dụng phụ')),
                ('contraindications', models.TextField(blank=True, verbose_name='Chống chỉ định')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá')),
                ('stock', models.IntegerField(default=0, verbose_name='Số lượng tồn kho')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Nhà sản xuất')),
                ('expiry_date', models.DateField(verbose_name='Ngày hết hạn')),
                ('image', models.ImageField(blank=True, null=True, upload_to='drugs/', verbose_name='Hình ảnh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='pharmacy.drugcategory', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Thuốc',
                'verbose_name_plural': 'Thuốc',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Số lượng')),
                ('batch_number', models.CharField(max_length=50, verbose_name='Số lô')),
                ('expiry_date', models.DateField(verbose_name='Ngày hết hạn')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá nhập')),
                ('supplier', models.CharField(max_length=100, verbose_name='Nhà cung cấp')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='pharmacy.drug', verbose_name='Thuốc')),
            ],
            options={
                'verbose_name': 'Nhập kho',
                'verbose_name_plural': 'Nhập kho',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('approved', 'Đã duyệt'), ('dispensed', 'Đã cấp phát'), ('cancelled', 'Đã hủy')], default='pending', max_length=10, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='diagnosis.diagnosis', verbose_name='Chẩn đoán')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='Bác sĩ')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='Bệnh nhân')),
            ],
            options={
                'verbose_name': 'Đơn thuốc',
                'verbose_name_plural': 'Đơn thuốc',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Số lượng')),
                ('dosage', models.CharField(max_length=100, verbose_name='Liều lượng')),
                ('frequency', models.CharField(max_length=100, verbose_name='Tần suất')),
                ('duration', models.CharField(max_length=100, verbose_name='Thời gian dùng')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_items', to='pharmacy.drug', verbose_name='Thuốc')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.prescription', verbose_name='Đơn thuốc')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn thuốc',
                'verbose_name_plural': 'Chi tiết đơn thuốc',
            },
        ),
    ]
