# Generated by Django 5.0.2 on 2025-03-18 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_medicine_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='prescription',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_name',
            field=models.CharField(default='Bệnh nhân', max_length=200),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='instructions',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='unit',
            field=models.CharField(default='viên', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('unit', models.CharField(default='viên', max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medicine')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.transaction')),
            ],
        ),
    ]
