# Generated by Django 5.0.2 on 2025-03-18 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_transaction_updated_at_alter_transaction_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('sale', 'Bán hàng'), ('purchase', 'Nhập hàng'), ('return', 'Trả hàng')], default='sale', max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='unit',
            field=models.CharField(default='viên', max_length=50),
        ),
    ]
