# Generated by Django 5.0.2 on 2025-05-11 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_prescription_patient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_drug', models.TextField(verbose_name='Thuốc được khuyến nghị')),
                ('disease', models.CharField(max_length=255, verbose_name='Bệnh được chẩn đoán')),
                ('symptoms', models.TextField(verbose_name='Các triệu chứng')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('completed', 'Đã hoàn thành')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Lý do từ chối')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_requests', to=settings.AUTH_USER_MODEL)),
                ('pharmacist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handled_prescription_requests', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_source', to='pharmacy.prescription')),
            ],
            options={
                'verbose_name': 'Yêu cầu kê đơn thuốc',
                'verbose_name_plural': 'Yêu cầu kê đơn thuốc',
            },
        ),
    ]
