# Generated by Django 5.0.2 on 2025-05-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Quản trị viên'), ('web_manager', 'Quản lý website'), ('doctor', 'Bác sĩ'), ('pharmacist', 'Dược sĩ'), ('patient', 'Bệnh nhân')], default='patient', max_length=20),
        ),
    ]
