# Generated by Django 5.0.2 on 2025-03-21 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_alter_transaction_created_at_and_more'),
        ('pos', '0002_remove_sale_customer_remove_sale_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='pharmacy.transaction'),
        ),
    ]
