# Generated by Django 5.0.2 on 2025-03-18 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên triệu chứng')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Triệu chứng',
                'verbose_name_plural': 'Triệu chứng',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên bệnh')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('severity', models.CharField(choices=[('L', 'Nhẹ'), ('M', 'Trung bình'), ('H', 'Nặng')], default='M', max_length=1, verbose_name='Mức độ nghiêm trọng')),
                ('treatment_guidelines', models.TextField(blank=True, verbose_name='Hướng dẫn điều trị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symptoms', models.ManyToManyField(related_name='diseases', to='diagnosis.symptom', verbose_name='Triệu chứng')),
            ],
            options={
                'verbose_name': 'Bệnh',
                'verbose_name_plural': 'Bệnh',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('confidence_score', models.FloatField(default=0.0, verbose_name='Độ tin cậy')),
                ('diagnosis_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày chẩn đoán')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_diagnoses', to=settings.AUTH_USER_MODEL, verbose_name='Bác sĩ')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to=settings.AUTH_USER_MODEL, verbose_name='Bệnh nhân')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='diagnosis.disease', verbose_name='Bệnh được chẩn đoán')),
                ('symptoms', models.ManyToManyField(related_name='diagnoses', to='diagnosis.symptom', verbose_name='Triệu chứng')),
            ],
            options={
                'verbose_name': 'Chẩn đoán',
                'verbose_name_plural': 'Chẩn đoán',
                'ordering': ['-diagnosis_date'],
            },
        ),
    ]
