# Generated by Django 5.0.2 on 2025-03-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='severity',
            field=models.CharField(choices=[('low', 'Nhẹ'), ('medium', 'Trung bình'), ('high', 'Nặng')], default='medium', max_length=10, verbose_name='Mức độ nghiêm trọng'),
        ),
    ]
