# Generated by Django 5.0.2 on 2025-05-25 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_alter_disease_severity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='doctor',
        ),
    ]
